import { useEffect, useState } from 'react';
import {
  Zap, CheckCircle, Server, Cloud, Cpu, Sparkles
} from 'lucide-react';
import HeroVideoBg from '../components/HeroVideoBg';
import Navbar from '../components/Navbar';
import logoDark from '../assets/logo_dark.avif';

const NHG = '"Neue Haas Grotesk Display Pro 55 Roman", "Neue Haas Grotesk Text Pro", "Helvetica Neue", Helvetica, Arial, sans-serif';
const PRIMARY = '#00E5FF';

const subLinks = [
  { label: 'NativeSOC Approach', href: '/nativesocapproach' },
  { label: 'NativeSOC Features', href: '/nativesocfeatures' },
  { label: 'NativeSOC Architecture', href: '/nativesocarchitecture' },
  { label: 'How it Works', href: '/howitworks' },
  { label: 'Why NativeSOC', href: '/whynativesoc' },
];

interface FeatureItem {
  title: string;
  desc: string;
  points: string[];
}

const endpointFeatures: FeatureItem[] = [
  {
    title: 'Security Configuration Assessment (SCA)',
    desc: 'Assessing system settings and configurations to ensure they comply with security best practices and standards. NativeSOC identifies misconfigurations and vulnerabilities on monitored endpoints to efficiently manage attack surfaces.',
    points: ['Vulnerability & misconfig scans', 'Integrated compliance tracking', 'System hardening insights', 'Continuous monitoring audits']
  },
  {
    title: 'Malware Detection Engine',
    desc: 'Advanced strategies and tools to detect ransomware, rootkits, spyware, adware, trojans, viruses, and worms across all enterprise assets.',
    points: ['Real-time cross-platform scans', 'Ransomware behavioral blocking', 'Rootkit module analysis', 'Advanced rulesets & decoders']
  },
  {
    title: 'File Integrity Monitoring (FIM)',
    desc: 'Monitors and alerts on unauthorized changes to critical system files, baseline configurations, registries, and system directories in real time.',
    points: ['Real-time file change alerts', 'Security breach indicator detection', 'Regulatory file tracking', 'Cross-platform FIM modules']
  }
];

const intelFeatures: FeatureItem[] = [
  {
    title: 'Proactive Threat Hunting',
    desc: 'Equips organizations with the necessary advanced log indexing, querying, and tactics hunting to detect persistent attacks and threat actor activities.',
    points: ['MITRE ATT&CK framework mapping', 'Log retention & fast queries', 'Custom command monitoring', 'Tailored alert rulesets']
  },
  {
    title: 'Real-Time Log Data Analysis',
    desc: 'Aggregates, analyzes, and stores logs generated by networks, databases, endpoints, and applications to maintain continuous compliance.',
    points: ['Security threat detection', 'Third-party integrations API', 'Holistic IT infrastructure views', 'High-performance scalability']
  },
  {
    title: 'Vulnerability Detection suite',
    desc: 'A complete suite of modules using a risk-based approach to prioritize vulnerabilities, allowing security teams to focus on critical errors.',
    points: ['Risk-based prioritization math', 'Automated asset vulnerability scans', 'Multi-platform compatibility', 'SCA integration metrics']
  }
];

const operationsFeatures: FeatureItem[] = [
  {
    title: 'Automated Incident Response',
    desc: 'Enables actions and containment processes to respond to threats in real time, mitigating cyberattack impacts on corporate workloads.',
    points: ['SOAR playbook execution', 'Reduced security threat dwell times', 'Streamlined analyst workflows', 'Incident mitigation containment']
  },
  {
    title: 'Regulatory Compliance Auditing',
    desc: 'Simplifies fulfillment of strict compliance audits, offering pre-configured mappings for PCI DSS, HIPAA, GDPR, and other key standards.',
    points: ['Audit infrastructure baselining', 'Compliance activity streaming', 'Customizable policy enforcement', 'Automated compliance reports']
  },
  {
    title: 'Proactive IT Hygiene',
    desc: 'Maintains baseline system configurations, software inventory tracking, and vulnerability patching schedules across multi-hybrid environments.',
    points: ['Comprehensive system inventories', 'SCA configuration assessments', 'Malware detection mapping', 'Vulnerability management integration']
  }
];

const cloudFeatures: FeatureItem[] = [
  {
    title: 'Container & Kubernetes Security',
    desc: 'Provides real-time runtime monitoring, microservice inventory tracking, and orchestration platform auditing for secure container workloads.',
    points: ['K8s orchestration auditing', 'Runtime process monitoring', 'Container inventory details', 'Container health metrics']
  },
  {
    title: 'Cloud Security Posture Management (CSPM)',
    desc: 'Evaluates and maintains robust cloud platform security postures by identifying configuration risks and ensuring continuous compliance.',
    points: ['Direct cloud API connectors', 'Posture configuration assessment', 'Continuous compliance mapping', 'Automated incident alerts']
  },
  {
    title: 'Cloud Workload Protection (CWPP)',
    desc: 'Secures distributed serverless workloads and host instances running in Amazon Web Services (AWS), Microsoft Azure, Google Cloud (GCP), and Office 365.',
    points: ['AWS CloudTrail log analysis', 'Azure AD login anomaly detection', 'GCP audit stream collection', 'Workload file integrity checks']
  }
];

export default function NativeSOCFeaturesPage() {
  const [isDark, _setIsDark] = useState(false);
  const [activeTab, setActiveTab] = useState<'endpoint' | 'intel' | 'ops' | 'cloud'>('endpoint');

  /* Sync dark class */
  useEffect(() => {
    const root = document.documentElement;
    isDark ? root.classList.add('dark') : root.classList.remove('dark');
  }, [isDark]);

  /* Scroll to top on mount */
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'instant' });
  }, []);

  const getActiveFeatures = () => {
    switch (activeTab) {
      case 'endpoint': return endpointFeatures;
      case 'intel': return intelFeatures;
      case 'ops': return operationsFeatures;
      case 'cloud': return cloudFeatures;
    }
  };

  const getTabIcon = () => {
    switch (activeTab) {
      case 'endpoint': return <Server className="w-5 h-5" />;
      case 'intel': return <Cpu className="w-5 h-5" />;
      case 'ops': return <Zap className="w-5 h-5" />;
      case 'cloud': return <Cloud className="w-5 h-5" />;
    }
  };

  return (
    <div className="min-h-screen transition-colors duration-500 text-white" style={{ background: '#0A0F1F' }}>

      {/* ══ NAVBAR ══ */}
      <Navbar
        backLink="/nativesoc"
        subLinks={subLinks}
        ctaText="Get Demo"
        ctaLink="/#contact"
      />

      {/* ══ HERO ══ */}
      <section className="relative pt-28 pb-16 sm:pt-36 sm:pb-20 overflow-hidden">
        <HeroVideoBg />
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[850px] h-[550px] rounded-full opacity-[0.07] dark:opacity-[0.05]"
            style={{ background: `radial-gradient(ellipse, ${PRIMARY} 0%, transparent 70%)` }} />
        </div>

        <div className="relative max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10">
          <div className="inline-flex items-center gap-2 bg-[rgba(0,229,255,0.08)] border border-[rgba(0,229,255,0.15)] rounded-full px-4 py-1.5 mb-8">
            <Sparkles className="w-3.5 h-3.5 text-[#00E5FF]" />
            <span className="text-xs font-bold text-[#00E5FF] tracking-wider uppercase">Platform Capabilities</span>
          </div>

          <div className="max-w-3xl">
            <h1
              className="font-normal text-white mb-6"
              style={{
                fontFamily: NHG,
                fontSize: 'clamp(2.2rem, 5.5vw, 4.5rem)',
                lineHeight: 0.95,
                letterSpacing: '-0.03em',
              }}
            >
              Granular Security <br />
              <span className="text-[#00E5FF] font-medium">Features Ecosystem.</span>
            </h1>
            <p className="text-sm sm:text-base text-[#7a9bb5] leading-relaxed">
              Explore the advanced features powering the six integrated layers of NativeSOC. From host-level audits
              to container health logs, manage and prioritize threats seamlessly.
            </p>
          </div>
        </div>
      </section>

      {/* ══ INTERACTIVE TABS & GRID ══ */}
      <section >
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10">

          {/* Tab Switcher */}
          <div className="flex justify-center gap-2 flex-wrap mb-16">
            {[
              { id: 'endpoint', label: 'Endpoint Security', icon: <Server className="w-3.5 h-3.5" /> },
              { id: 'intel', label: 'Threat Intelligence', icon: <Cpu className="w-3.5 h-3.5" /> },
              { id: 'ops', label: 'Security Operations', icon: <Zap className="w-3.5 h-3.5" /> },
              { id: 'cloud', label: 'Cloud Security', icon: <Cloud className="w-3.5 h-3.5" /> },
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`inline-flex items-center gap-1.5 text-xs font-semibold px-4 py-2.5 rounded-full border transition-all duration-200 ${activeTab === tab.id ? 'bg-[#0A0F1F] text-white border-transparent' : 'text-[#7a9bb5] border-[rgba(0,229,255,0.1)] hover:border-[rgba(0,229,255,0.3)]'}`}
                style={{ background: '#0A0F1F' }}
              >
                {tab.icon}
                {tab.label}
              </button>
            ))}
          </div>

          {/* Features Detail Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {getActiveFeatures().map((f) => (
              <div
                key={f.title}
                style={{ background: '#0A0F1F' }} className="p-6 sm:p-8 rounded-3xl border border-[rgba(0,229,255,0.1)] flex flex-col justify-between hover:shadow-lg transition-all duration-300"
              >
                <div>
                  <div className="w-10 h-10 rounded-xl bg-[rgba(0,229,255,0.12)] flex items-center justify-center text-[#00E5FF] mb-6">
                    {getTabIcon()}
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-4" style={{ fontFamily: NHG }}>
                    {f.title}
                  </h3>
                  <p className="text-xs sm:text-sm text-[#7a9bb5] leading-relaxed mb-6">
                    {f.desc}
                  </p>
                </div>

                <div className="pt-6 border-t border-[rgba(0,229,255,0.1)] space-y-3">
                  <span className="text-[10px] font-bold tracking-widest text-[#00E5FF] uppercase">Technical Metrics</span>
                  <ul className="space-y-2">
                    {f.points.map(pt => (
                      <li key={pt} className="flex items-start gap-2 text-xs text-white">
                        <CheckCircle className="w-3.5 h-3.5 text-[#00E5FF] mt-0.5 flex-shrink-0" />
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* ══ FOOTER ══ */}
      <footer style={{ background: '#0A0F1F' }} className="border-t border-[rgba(0,229,255,0.1)] transition-colors duration-500">
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10 py-5 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex flex-col sm:flex-row items-center gap-3">
            <img src={logoDark} style={{ opacity: 0.8 }} alt="NativeDefence Logo" className="h-7 w-auto opacity-70 transition-all duration-300" />
            <p className="text-xs text-[#7a9bb5]/40">
              Copyright 2023  © NATIVEDEFENCE TECH LLP. All rights reserved.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            <span className="text-xs text-[#7a9bb5]/40">Granular Auditing Operations Active</span>
          </div>
        </div>
      </footer>

    </div>
  );
}
