import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import logoLight from '../assets/logo_light.png';
import logoDark from '../assets/logo_dark.png';
import {
  ArrowLeft, Zap, CheckCircle, Server, Cloud, Cpu,
  Sparkles, Sun, Moon, Menu, X
} from 'lucide-react';

const NHG = '"Neue Haas Grotesk Display Pro 55 Roman", "Neue Haas Grotesk Text Pro", "Helvetica Neue", Helvetica, Arial, sans-serif';
const PRIMARY = '#336443';

const subLinks = [
  { label: 'NativeSOC Approach', href: '/nativesocapproach' },
  { label: 'NativeSOC Features', href: '/nativesocfeatures' },
  { label: 'NativeSOC Architecture', href: '/nativesocarchitecture' },
  { label: 'How it Works', href: '/howitworks' },
  { label: 'Why NativeSOC', href: '/whynativesoc' },
];

interface FeatureItem {
  title: string;
  desc: string;
  points: string[];
}

const endpointFeatures: FeatureItem[] = [
  {
    title: 'Security Configuration Assessment (SCA)',
    desc: 'Assessing system settings and configurations to ensure they comply with security best practices and standards. NativeSOC identifies misconfigurations and vulnerabilities on monitored endpoints to efficiently manage attack surfaces.',
    points: ['Vulnerability & misconfig scans', 'Integrated compliance tracking', 'System hardening insights', 'Continuous monitoring audits']
  },
  {
    title: 'Malware Detection Engine',
    desc: 'Advanced strategies and tools to detect ransomware, rootkits, spyware, adware, trojans, viruses, and worms across all enterprise assets.',
    points: ['Real-time cross-platform scans', 'Ransomware behavioral blocking', 'Rootkit module analysis', 'Advanced rulesets & decoders']
  },
  {
    title: 'File Integrity Monitoring (FIM)',
    desc: 'Monitors and alerts on unauthorized changes to critical system files, baseline configurations, registries, and system directories in real time.',
    points: ['Real-time file change alerts', 'Security breach indicator detection', 'Regulatory file tracking', 'Cross-platform FIM modules']
  }
];

const intelFeatures: FeatureItem[] = [
  {
    title: 'Proactive Threat Hunting',
    desc: 'Equips organizations with the necessary advanced log indexing, querying, and tactics hunting to detect persistent attacks and threat actor activities.',
    points: ['MITRE ATT&CK framework mapping', 'Log retention & fast queries', 'Custom command monitoring', 'Tailored alert rulesets']
  },
  {
    title: 'Real-Time Log Data Analysis',
    desc: 'Aggregates, analyzes, and stores logs generated by networks, databases, endpoints, and applications to maintain continuous compliance.',
    points: ['Security threat detection', 'Third-party integrations API', 'Holistic IT infrastructure views', 'High-performance scalability']
  },
  {
    title: 'Vulnerability Detection suite',
    desc: 'A complete suite of modules using a risk-based approach to prioritize vulnerabilities, allowing security teams to focus on critical errors.',
    points: ['Risk-based prioritization math', 'Automated asset vulnerability scans', 'Multi-platform compatibility', 'SCA integration metrics']
  }
];

const operationsFeatures: FeatureItem[] = [
  {
    title: 'Automated Incident Response',
    desc: 'Enables actions and containment processes to respond to threats in real time, mitigating cyberattack impacts on corporate workloads.',
    points: ['SOAR playbook execution', 'Reduced security threat dwell times', 'Streamlined analyst workflows', 'Incident mitigation containment']
  },
  {
    title: 'Regulatory Compliance Auditing',
    desc: 'Simplifies fulfillment of strict compliance audits, offering pre-configured mappings for PCI DSS, HIPAA, GDPR, and other key standards.',
    points: ['Audit infrastructure baselining', 'Compliance activity streaming', 'Customizable policy enforcement', 'Automated compliance reports']
  },
  {
    title: 'Proactive IT Hygiene',
    desc: 'Maintains baseline system configurations, software inventory tracking, and vulnerability patching schedules across multi-hybrid environments.',
    points: ['Comprehensive system inventories', 'SCA configuration assessments', 'Malware detection mapping', 'Vulnerability management integration']
  }
];

const cloudFeatures: FeatureItem[] = [
  {
    title: 'Container & Kubernetes Security',
    desc: 'Provides real-time runtime monitoring, microservice inventory tracking, and orchestration platform auditing for secure container workloads.',
    points: ['K8s orchestration auditing', 'Runtime process monitoring', 'Container inventory details', 'Container health metrics']
  },
  {
    title: 'Cloud Security Posture Management (CSPM)',
    desc: 'Evaluates and maintains robust cloud platform security postures by identifying configuration risks and ensuring continuous compliance.',
    points: ['Direct cloud API connectors', 'Posture configuration assessment', 'Continuous compliance mapping', 'Automated incident alerts']
  },
  {
    title: 'Cloud Workload Protection (CWPP)',
    desc: 'Secures distributed serverless workloads and host instances running in Amazon Web Services (AWS), Microsoft Azure, Google Cloud (GCP), and Office 365.',
    points: ['AWS CloudTrail log analysis', 'Azure AD login anomaly detection', 'GCP audit stream collection', 'Workload file integrity checks']
  }
];

export default function NativeSOCFeaturesPage() {
  const [isDark, setIsDark] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<'endpoint' | 'intel' | 'ops' | 'cloud'>('endpoint');

  /* Sync dark class */
  useEffect(() => {
    const root = document.documentElement;
    isDark ? root.classList.add('dark') : root.classList.remove('dark');
  }, [isDark]);

  /* Scroll to top on mount */
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'instant' });
  }, []);

  const getActiveFeatures = () => {
    switch (activeTab) {
      case 'endpoint': return endpointFeatures;
      case 'intel': return intelFeatures;
      case 'ops': return operationsFeatures;
      case 'cloud': return cloudFeatures;
    }
  };

  const getTabIcon = () => {
    switch (activeTab) {
      case 'endpoint': return <Server className="w-5 h-5" />;
      case 'intel': return <Cpu className="w-5 h-5" />;
      case 'ops': return <Zap className="w-5 h-5" />;
      case 'cloud': return <Cloud className="w-5 h-5" />;
    }
  };

  return (
    <div className="min-h-screen bg-white dark:bg-[#0e150d] transition-colors duration-500 text-[#1f2a1d] dark:text-[#c5d9c3]">

      {/* ══ NAVBAR ══ */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 dark:bg-[#0e150d]/80 backdrop-blur-xl border-b border-black/5 dark:border-white/5">
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10 h-16 flex items-center justify-between">

          {/* Logo & Back */}
          <div className="flex items-center gap-4">
            <Link
              to="/nativesoc"
              className="flex items-center gap-1.5 text-sm font-medium text-[#4b5b47] dark:text-[#8a9e86] hover:text-[#1f2a1d] dark:hover:text-white transition-colors duration-200"
            >
              <ArrowLeft className="w-4 h-4" />
              Back
            </Link>
            <span className="w-px h-4 bg-[#1f2a1d]/15 dark:bg-white/15" />
            <Link to="/" className="flex items-center">
              <img
                src={isDark ? logoDark : logoLight}
                alt="NativeDefence Logo"
                className="transition-all duration-300 object-contain"
                style={isDark
                  ? { width: '135px', height: '40px' }
                  : { height: '40px', width: 'auto' }
                }
              />
            </Link>
          </div>

          {/* Desktop Links */}
          <div className="hidden lg:flex items-center gap-1">
            {subLinks.map(l => (
              <Link
                key={l.href}
                to={l.href}
                className={`text-xs font-semibold px-3 py-1.5 rounded-full transition-all duration-200 whitespace-nowrap ${l.href === '/nativesocfeatures' ? 'bg-[#1f2a1d] text-white dark:bg-[#336443]' : 'text-[#4b5b47] dark:text-[#8a9e86] hover:text-[#1f2a1d] dark:hover:text-white hover:bg-[#f7f6f2] dark:hover:bg-[#1f2a1d]'}`}
              >
                {l.label}
              </Link>
            ))}
          </div>

          {/* Nav Actions */}
          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsDark(d => !d)}
              className="flex items-center justify-center w-8 h-8 rounded-full bg-[#f7f6f2] dark:bg-[#1f2a1d] border border-black/8 dark:border-white/8 relative"
            >
              <Sun className={`w-3.5 h-3.5 text-[#1f2a1d] dark:text-white absolute transition-all duration-300 ${isDark ? 'opacity-100' : 'opacity-0 rotate-90'}`} />
              <Moon className={`w-3.5 h-3.5 text-[#1f2a1d] dark:text-white absolute transition-all duration-300 ${isDark ? 'opacity-0 -rotate-90' : 'opacity-100'}`} />
            </button>

            <Link
              to="/#contact"
              className="hidden sm:flex items-center gap-1.5 bg-[#1f2a1d] hover:bg-[#2a3827] dark:bg-[#336443] dark:hover:bg-[#2a5438] text-white text-xs font-semibold px-4 py-2 rounded-full transition-colors duration-200"
            >
              Get Demo
            </Link>

            <button
              onClick={() => setMenuOpen(v => !v)}
              className="lg:hidden flex items-center justify-center w-8 h-8 rounded-full bg-[#f7f6f2] dark:bg-[#1f2a1d] border border-black/8 dark:border-white/8 relative"
            >
              <Menu className={`w-4 h-4 text-[#1f2a1d] dark:text-white absolute transition-all duration-200 ${menuOpen ? 'opacity-0' : 'opacity-100'}`} />
              <X className={`w-4 h-4 text-[#1f2a1d] dark:text-white absolute transition-all duration-200 ${menuOpen ? 'opacity-100' : 'opacity-0'}`} />
            </button>
          </div>
        </div>

        {/* Mobile Drawer */}
        <div className={`lg:hidden overflow-hidden transition-all duration-400 ease-[cubic-bezier(0.22,1,0.36,1)] ${menuOpen ? 'max-h-80' : 'max-h-0'}`}>
          <div className="px-4 pb-4 flex flex-col gap-1 border-t border-black/5 dark:border-white/5 pt-3">
            {subLinks.map(l => (
              <Link
                key={l.href}
                to={l.href}
                onClick={() => setMenuOpen(false)}
                className={`text-left text-sm font-medium py-2.5 border-b border-black/5 dark:border-white/5 last:border-0 ${l.href === '/nativesocfeatures' ? 'text-[#336443] dark:text-[#85AB8B] font-semibold' : 'text-[#4b5b47] dark:text-[#8a9e86]'}`}
              >
                {l.label}
              </Link>
            ))}
            <Link
              to="/#contact"
              onClick={() => setMenuOpen(false)}
              className="mt-2 block text-center bg-[#1f2a1d] text-white text-sm font-semibold py-3 rounded-full"
            >
              Get Demo
            </Link>
          </div>
        </div>
      </nav>

      {/* ══ HERO ══ */}
      <section className="relative pt-28 pb-16 sm:pt-36 sm:pb-20 overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[850px] h-[550px] rounded-full opacity-[0.07] dark:opacity-[0.05]"
            style={{ background: `radial-gradient(ellipse, ${PRIMARY} 0%, transparent 70%)` }} />
        </div>

        <div className="relative max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10">
          <div className="inline-flex items-center gap-2 bg-[#f0f7f1] dark:bg-[#141d13] border border-[#336443]/15 dark:border-white/10 rounded-full px-4 py-1.5 mb-8">
            <Sparkles className="w-3.5 h-3.5 text-[#336443] dark:text-[#85AB8B]" />
            <span className="text-xs font-bold text-[#336443] dark:text-[#85AB8B] tracking-wider uppercase">Platform Capabilities</span>
          </div>

          <div className="max-w-3xl">
            <h1
              className="font-normal text-[#1f2a1d] dark:text-white mb-6"
              style={{
                fontFamily: NHG,
                fontSize: 'clamp(2.2rem, 5.5vw, 4.5rem)',
                lineHeight: 0.95,
                letterSpacing: '-0.03em',
              }}
            >
              Granular Security <br />
              <span className="text-[#336443] dark:text-[#85AB8B] font-medium">Features Ecosystem.</span>
            </h1>
            <p className="text-sm sm:text-base text-[#4b5b47] dark:text-[#8a9e86] leading-relaxed">
              Explore the advanced features powering the six integrated layers of NativeSOC. From host-level audits
              to container health logs, manage and prioritize threats seamlessly.
            </p>
          </div>
        </div>
      </section>

      {/* ══ INTERACTIVE TABS & GRID ══ */}
      <section className="bg-[#f7f6f2] dark:bg-[#141d13] py-16 sm:py-24 transition-colors duration-500">
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10">

          {/* Tab Switcher */}
          <div className="flex justify-center gap-2 flex-wrap mb-16">
            {[
              { id: 'endpoint', label: 'Endpoint Security', icon: <Server className="w-3.5 h-3.5" /> },
              { id: 'intel', label: 'Threat Intelligence', icon: <Cpu className="w-3.5 h-3.5" /> },
              { id: 'ops', label: 'Security Operations', icon: <Zap className="w-3.5 h-3.5" /> },
              { id: 'cloud', label: 'Cloud Security', icon: <Cloud className="w-3.5 h-3.5" /> },
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`inline-flex items-center gap-1.5 text-xs font-semibold px-4 py-2.5 rounded-full border transition-all duration-200 ${activeTab === tab.id ? 'bg-[#1f2a1d] text-white border-transparent' : 'bg-white dark:bg-[#0e150d] text-[#4b5b47] dark:text-[#8a9e86] border-black/5 dark:border-white/5 hover:border-[#336443]/30'}`}
              >
                {tab.icon}
                {tab.label}
              </button>
            ))}
          </div>

          {/* Features Detail Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {getActiveFeatures().map((f) => (
              <div
                key={f.title}
                className="bg-white dark:bg-[#0e150d] p-6 sm:p-8 rounded-3xl border border-black/5 dark:border-white/5 flex flex-col justify-between hover:shadow-lg transition-all duration-300"
              >
                <div>
                  <div className="w-10 h-10 rounded-xl bg-[#336443]/10 dark:bg-[#336443]/20 flex items-center justify-center text-[#336443] dark:text-[#85AB8B] mb-6">
                    {getTabIcon()}
                  </div>
                  <h3 className="text-lg font-semibold text-[#1f2a1d] dark:text-white mb-4" style={{ fontFamily: NHG }}>
                    {f.title}
                  </h3>
                  <p className="text-xs sm:text-sm text-[#4b5b47] dark:text-[#8a9e86] leading-relaxed mb-6">
                    {f.desc}
                  </p>
                </div>

                <div className="pt-6 border-t border-black/5 dark:border-white/5 space-y-3">
                  <span className="text-[10px] font-bold tracking-widest text-[#336443] dark:text-[#85AB8B] uppercase">Technical Metrics</span>
                  <ul className="space-y-2">
                    {f.points.map(pt => (
                      <li key={pt} className="flex items-start gap-2 text-xs text-[#1f2a1d] dark:text-[#c5d9c3]">
                        <CheckCircle className="w-3.5 h-3.5 text-[#336443] mt-0.5 flex-shrink-0" />
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* ══ FOOTER ══ */}
      <footer className="bg-white dark:bg-[#0e150d] border-t border-[#1f2a1d]/10 dark:border-white/10 transition-colors duration-500">
        <div className="max-w-[1440px] mx-auto px-4 sm:px-6 md:px-10 py-5 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex flex-col sm:flex-row items-center gap-3">
            <img src={isDark ? logoDark : logoLight} alt="NativeDefence Logo" className="h-7 w-auto opacity-70 dark:opacity-85 transition-all duration-300" />
            <p className="text-xs text-[#4b5b47]/50 dark:text-[#8a9e86]/40">
              Copyright 2023  © NATIVEDEFENCE TECH LLP. All rights reserved.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            <span className="text-xs text-[#4b5b47]/50 dark:text-[#8a9e86]/40">Granular Auditing Operations Active</span>
          </div>
        </div>
      </footer>

    </div>
  );
}
